export const allVendor = [
  {
    id: 1,
    image: "https://i.ibb.co.com/sJDksb7Y/image-8.png",
    name: "Johan Smith",
    level: "Level-1",
    commission: "6",
    completeDelivery: "44",
    cancelDelivery: "3",
    earning: "4000",
    address: "2118 Thornridge Cir. Miami ",
    status: "Active",
  },
  {
    id: 2,
    image: "https://i.ibb.co.com/sJDksb7Y/image-8.png",
    name: "Amira Lopez",
    level: "Level-2",
    commission: "5",
    completeDelivery: "39",
    cancelDelivery: "2",
    earning: "3500",
    address: "2118 Thornridge Cir. Miami ",
    status: "Active",
  },
  {
    id: 3,
    image: "https://i.ibb.co.com/sJDksb7Y/image-8.png",
    name: "Michael Chen",
    level: "Level-1",
    commission: "7",
    completeDelivery: "52",
    cancelDelivery: "5",
    earning: "4200",
    address: "2118 Thornridge Cir. Miami ",
    status: "Active",
  },
  {
    id: 4,
    image: "https://i.ibb.co.com/sJDksb7Y/image-8.png",
    name: "Sara Ahmed",
    level: "Level-3",
    commission: "4",
    completeDelivery: "28",
    cancelDelivery: "1",
    earning: "3100",
    address: "2118 Thornridge Cir. Miami ",
    status: "Active",
  },
  {
    id: 5,
    image: "https://i.ibb.co.com/sJDksb7Y/image-8.png",
    name: "David Kim",
    level: "Level-2",
    commission: "6",
    completeDelivery: "60",
    cancelDelivery: "4",
    earning: "4700",
    address: "2118 Thornridge Cir. Miami ",
    status: "Active",
  },
  {
    id: 6,
    image: "https://i.ibb.co.com/sJDksb7Y/image-8.png",
    name: "Fatima Khan",
    level: "Level-1",
    commission: "5",
    completeDelivery: "33",
    cancelDelivery: "2",
    earning: "3400",
    address: "2118 Thornridge Cir. Miami ",
    status: "Active",
  },
  {
    id: 7,
    image: "https://i.ibb.co.com/sJDksb7Y/image-8.png",
    name: "Leo Fernandez",
    level: "Level-2",
    commission: "6",
    completeDelivery: "48",
    cancelDelivery: "3",
    earning: "3900",
    address: "2118 Thornridge Cir. Miami ",
    status: "Active",
  },
  //   {
  //     id: 8,
  //     image: "https://i.ibb.co.com/sJDksb7Y/image-8.png",
  //     name: "Emily Brown",
  //     level: "Level-3",
  //     commission: "5",
  //     completeDelivery: "40",
  //     cancelDelivery: "2",
  //     earning: "3600",
  // address:"2118 Thornridge Cir. Miami ",
  // status:"Active"
  //   },
  //   {
  //     id: 9,
  //     image: "https://i.ibb.co.com/sJDksb7Y/image-8.png",
  //     name: "Noah Wilson",
  //     level: "Level-1",
  //     commission: "7",
  //     completeDelivery: "55",
  //     cancelDelivery: "6",
  //     earning: "4500",
  // address:"2118 Thornridge Cir. Miami ",
  // status:"Active"
  //   },
];

export const transaction = [
  {
    sl: "01",
    orderId: "#123456789",
    vendorName: "Johan Smith",
    totalPrice: "TSH 10,000",
    receivedAt: "15 July 2025 at 10 am",
    deliveryAt: "15 July 2025 at 10 am",
    deliveryStatus: "Success",
    paymentStatus: "Pending",
  },
  {
    sl: "02",
    orderId: "#123456789",
    vendorName: "Johan Smith",
    totalPrice: "TSH 10,000",
    receivedAt: "15 July 2025 at 10 am",
    deliveryAt: "15 July 2025 at 10 am",
    deliveryStatus: "Success",
    paymentStatus: "Pending",
  },
  {
    sl: "03",
    orderId: "#123456789",
    vendorName: "Johan Smith",
    totalPrice: "TSH 10,000",
    receivedAt: "15 July 2025 at 10 am",
    deliveryAt: "15 July 2025 at 10 am",
    deliveryStatus: "Success",
    paymentStatus: "Pending",
  },
  {
    sl: "04",
    orderId: "#123456789",
    vendorName: "Johan Smith",
    totalPrice: "TSH 10,000",
    receivedAt: "15 July 2025 at 10 am",
    deliveryAt: "15 July 2025 at 10 am",
    deliveryStatus: "Success",
    paymentStatus: "Pending",
  },
];

// vendor modal data
export const vendorData = [
  {
    label: "Vendor Address",
    value: "Mandela Road Mchikichini, Ilala, Ilala",
  },
  { label: "Joining Date", value: "20 July 2025" },
  { label: "Vendor Phone Number", value: "+255 712 345 678" },
  { label: "Vendor TIN Number", value: "TZN–DR–984152" },
  { label: "License Expiry Date", value: "2026–04–15" },
  { label: "Business Address", value: "Mandela Road Mchikichini," },
  { label: "Business Shop Name", value: "Fashion World" },
  { label: "Vendor Account Number", value: "01010202303045" },
];
